### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by waxnkw** [Scarecrow0/BGNN-SGG#2]
Thanks for your paper! The model looks very effective in unbiased scene graph generation according to the paper. When will the code be released? I am looking forward to it!

**Comment by Scarecrow0** [comment]
Hi!
Thanks for interested in our work.
The codebase is quite messy and still needs some time to refactor. 
I'm currently working on another project, I will finish the refactor in few weeks after the NeurIPS deadline.
This work is developed based on https://github.com/KaihuaTang/Scene-Graph-Benchmark.pytorch. You can try to re-implement the method by yourself first, feel free to ask me questions if you have anything unclear in the paper.

**Comment by Scarecrow0** [comment]
Please check out our PySGG.
https://github.com/SHTUPLUS/PySGG
